package de.zeeman.sayingManager.data;
// default package
// Generated 25.10.2007 23:00:25 by Hibernate Tools 3.2.0.b11

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sayings generated by hbm2java
 */
@Entity
@Table(name = "Sayings", catalog = "Sayings", uniqueConstraints = @UniqueConstraint(columnNames = "Saying"))
public class Saying implements java.io.Serializable {
	private static final long serialVersionUID = 2439092723738113606L;
	private Integer id;
	private Author author;
	private String saying;

	public Saying() {
	}

	public Saying(Author author, String saying) {
		this.author = author;
		this.saying = saying;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "Id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "AuthorId", nullable = false)
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@Column(name = "Saying", unique = true, nullable = false, length = 65535)
	public String getSaying() {
		return this.saying;
	}

	public void setSaying(String saying) {
		this.saying = saying;
	}

	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(this.getSaying());
		sb.append("[").append(getAuthor().toString()).append("]");
		return sb.toString();
	}

}
